server:
  port: 8300

spring:
  datasource:
    username: root
    password: 123456
    #使用 MySQL连接驱动是8.0以上，需要在Url后面加上时区, GMT%2B8代表中国时区，不然报时区错误
    url: jdbc:mysql://127.0.0.1:3306/mp2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    # 注意： 新版本驱动包，要使用以下类作为驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: true
  mail:
    username: 575726653@qq.com
    password: xxx
    host: smtp.qq.com
    properties:
      smtp:
        ssl:
          enable: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:

com:
  ss:
    blog:
      name: hiSB
      title: hhhhh
      age: ${random.value} # 随机字符串
      number: ${random.int} # 随机int
      bignumber: ${random.long} # 随机long
      test1: ${random.int(10)} # 10以内的随机数
      test2: ${random.int[10,20]} # 10-20的随机数
