server:
  port: 8888

knife4j:
  enable: true
  basic:
    enable: true
    username: admin
    password: 123456
    setting:
      # Knife4j默认显示中文(zh-CN),如果开发者想直接显示英文(en-US)，在通过该配置进行设置即可
      language: en-US